server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mzx.entity                      # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://114.55.37.2:3306/SpringCloud8002              # 数据库名称
    username: root
    password: Mazhenxin123.
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

# 配置Eureka客户端  将当前服务注册进去Eureka服务中
eureka:
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002-hystrix
    prefer-ip-address: true     #访问路径可以显示IP地址
#增加info信息
info:
  app.name: mzx-microservicecloud-8002
  company.name: www.mzx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
#security:
#  basic:
#    enabled: false