server:
  port: 7001
  # 配置Eureka
eureka:
  instance:
    hostname: eureka7001.com          # Eureka服务端实例名称
  client:
    register-with-eureka: false  # 不需要向Eureka服务注册中心注册自己
    fetch-registry: false        # false表示自己就是注册中心，当前服务的职责就是维护服务，并不需要去检索服务
    service-url:
      #单机版defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/